### ISSUE TITLE
Add auction Label problem

### ISSUE THREAD

**Issue by alishanvr** [therightsol/12345-abc-test-l-auc#24]
There is a problem in add new action. after putting input, labels again came to original place. May be some class or div problem. 

please check image for more clarity. 

![01 - label problem](https://cloud.githubusercontent.com/assets/5610722/24567370/d44bb35c-1676-11e7-8c1a-9c12152ebb84.JPG)

**Comment by huzaifa-a** [comment]
ye mere pass nae aa raha 
![pakauction](https://cloud.githubusercontent.com/assets/16509078/24589547/bd07c9da-17f5-11e7-8099-8e41e31de203.png)
