### ISSUE TITLE
Go to back Link -- Optional

### ISSUE THREAD

**Issue by alishanvr** [therightsol/12345-abc-test-l-auc#29]
jb b hm koi new record add krty hai. example car ya car category. too success message ata hai laikn us k sath back jany ka link  ni aata ? yeh shyd mai nai pehly b kaha tha. agr ni kaha to plz esy kr dena. yeh Usi nai kaha hoa hai. 

agr easily hota hai too kr dena. wrna phr rehny dena.

**Comment by huzaifa-a** [comment]
kam to easy hai but ..............
phir say sari files change krni parni hai
koi nae 1 bar phir kr deta un

**Comment by alishanvr** [comment]
huzaifa ap nai yeh galat kr dia hai. es back button ko success k time py show krna tha check image

**Comment by alishanvr** [comment]
huzaifa mai nai oper b kaha hai k jb success message aye us time back button ya back jany k liya link. yaha py back sy murad woo listing ka page hai jaha py sb record show ho rha hai.



![back](https://cloud.githubusercontent.com/assets/5610722/24839249/4a58e9ac-1d70-11e7-9c64-65577a63bab4.JPG)
