### ISSUE TITLE
Car Module

### ISSUE THREAD

**Issue by alishanvr** [therightsol/12345-abc-test-l-auc#4]
Hi,

Please set below points for Car module. 

- Exterior and Interior color should be color picker. Not the text field
- Kilometers must not less than 0

Thank You,

**Comment by huzaifa-a** [comment]
done

**Comment by alishanvr** [comment]
Hi, good. But please add HTML validation also. html min attribute. as( min="0") in Kilometers.

Thank You,


![km](https://cloud.githubusercontent.com/assets/5610722/23808614/4c956b00-05ec-11e7-8e95-e2d59b72e20d.JPG)

**Comment by alishanvr** [comment]
Completed by me
